@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 12 17:47:05 +0100 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim AXI_top_tb_from_compiled_func_synth -key {Post-Synthesis:sim_1:Functional:AXI_top_tb_from_compiled} -tclbatch AXI_top_tb_from_compiled.tcl -view C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/AXI_top_tb_from_file_behav.wcfg -log simulate.log"
call xsim  AXI_top_tb_from_compiled_func_synth -key {Post-Synthesis:sim_1:Functional:AXI_top_tb_from_compiled} -tclbatch AXI_top_tb_from_compiled.tcl -view C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/AXI_top_tb_from_file_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
