# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/re2_copro/re2_copro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro || ORIG_REF_NAME==re2_copro} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_zynq_ultra_ps_e_0_0/re2_copro_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==re2_copro_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_re2_copro_0_1/re2_copro_re2_copro_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_re2_copro_0_1 || ORIG_REF_NAME==re2_copro_re2_copro_0_1} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_xbar_1/re2_copro_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_xbar_1 || ORIG_REF_NAME==re2_copro_xbar_1} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_ps8_0_axi_periph_1/re2_copro_ps8_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_ps8_0_axi_periph_1 || ORIG_REF_NAME==re2_copro_ps8_0_axi_periph_1} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_rst_ps8_0_100M_0/re2_copro_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_rst_ps8_0_100M_0 || ORIG_REF_NAME==re2_copro_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_auto_ds_0/re2_copro_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_auto_ds_0 || ORIG_REF_NAME==re2_copro_auto_ds_0} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_auto_pc_0/re2_copro_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_auto_pc_0 || ORIG_REF_NAME==re2_copro_auto_pc_0} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_auto_ds_1/re2_copro_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_auto_ds_1 || ORIG_REF_NAME==re2_copro_auto_ds_1} -quiet] -quiet

# IP: bd/re2_copro/ip/re2_copro_auto_pc_1/re2_copro_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==re2_copro_auto_pc_1 || ORIG_REF_NAME==re2_copro_auto_pc_1} -quiet] -quiet

# XDC: bd/re2_copro/re2_copro_ooc.xdc
