# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xczu3eg-sbva484-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.cache/wt [current_project]
set_property parent.project_path C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part avnet.com:ultra96v2:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/ip_repo/re2_copro_1
  c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/ip_repo/re2_copro_1.0
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/hdl/re2_copro_wrapper.v
add_files C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/re2_copro.bd
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_zynq_ultra_ps_e_0_0/re2_copro_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_zynq_ultra_ps_e_0_0/re2_copro_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_xbar_1/re2_copro_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_rst_ps8_0_100M_0/re2_copro_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_rst_ps8_0_100M_0/re2_copro_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_rst_ps8_0_100M_0/re2_copro_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_0/re2_copro_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_0/re2_copro_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_0/re2_copro_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_pc_0/re2_copro_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_1/re2_copro_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_1/re2_copro_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_ds_1/re2_copro_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/ip/re2_copro_auto_pc_1/re2_copro_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/danie/Documents/GitHub/regex_coprocessor_safe/proj/regex_copro/regex_copro.srcs/sources_1/bd/re2_copro/re2_copro_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top re2_copro_wrapper -part xczu3eg-sbva484-1-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef re2_copro_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file re2_copro_wrapper_utilization_synth.rpt -pb re2_copro_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
